<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Banner;
use Faker\Factory as Faker;

class BannerSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();

        $this->command->info('Creating banners with CDN images...');

        // Free CDN Image URLs
        $images = [
            // Industrial & Engineering
            'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&h=600&fit=crop&crop=center&auto=format',

            // Security & Safety
            'https://images.unsplash.com/photo-1558002038-1055907df827?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1619160151837-08b793c7b89b?w=1200&h=600&fit=crop&crop=center&auto=format',

            // Technology & Gadgets
            'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1555000006-2cf8f08aa3a0?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1558981285-6f0c94958bb6?w=1200&h=600&fit=crop&crop=center&auto=format',

            // Agriculture & Machinery
            'https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=1200&h=600&fit=crop&crop=center&auto=format',

            // Electrical & Electronics
            'https://images.unsplash.com/photo-1581092335874-0b7e5a2d20d8?w=1200&h=600&fit=crop&crop=center&auto=format',

            // Construction
            'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&h=600&fit=crop&crop=center&auto=format',

            // Safety Equipment
            'https://images.unsplash.com/photo-1619160151837-08b793c7b89b?w=1200&h=600&fit=crop&crop=center&auto=format',

            // Modern Technology
            'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=600&fit=crop&crop=center&auto=format',
            'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=1200&h=600&fit=crop&crop=center&auto=format',
        ];

        $banners = [
            [
                'title' => 'For a Safer Tomorrow',
                'badge' => '🔒 Featured Product',
                'description' => 'Advanced Engineering · Innovative Technology · Reliable Support',
                'image' => $images[0],
                'button_text' => 'Shop Now',
                'button_url' => '/products',
                'order' => 1,
                'status' => 'active',
                'start_date' => now()->subDays(10),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Year Warranty',
                'stat1_value' => '2',
                'stat2_label' => 'Year Free Service',
                'stat2_value' => '4',
                'stat3_label' => 'Support',
                'stat3_value' => '24/7',
                'text_color' => '#FFFFFF',
                'bg_color' => null,
                'button_color' => '#0637A1',
                'button_hover_color' => '#03246E',
            ],
            [
                'title' => 'Advanced Security Solutions',
                'badge' => '🚀 New Arrival',
                'description' => 'Protect your home and business with our cutting-edge security systems',
                'image' => $images[3],
                'button_text' => 'Learn More',
                'button_url' => '/products',
                'order' => 2,
                'status' => 'active',
                'start_date' => now()->subDays(5),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Happy Clients',
                'stat1_value' => '500+',
                'stat2_label' => 'Projects',
                'stat2_value' => '1000+',
                'stat3_label' => 'Rating',
                'stat3_value' => '4.9★',
                'text_color' => '#FFFFFF',
                'bg_color' => null,
                'button_color' => '#0658DC',
                'button_hover_color' => '#0637A1',
            ],
            [
                'title' => 'Industrial Engineering Excellence',
                'badge' => '⭐ Best Seller',
                'description' => 'High-quality engineering products for industrial applications',
                'image' => $images[1],
                'button_text' => 'View Products',
                'button_url' => '/products',
                'order' => 3,
                'status' => 'active',
                'start_date' => now()->subDays(3),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Products',
                'stat1_value' => '100+',
                'stat2_label' => 'Brands',
                'stat2_value' => '30+',
                'stat3_label' => 'Warranty',
                'stat3_value' => '5 Years',
                'text_color' => '#FFFFFF',
                'bg_color' => null,
                'button_color' => '#03246E',
                'button_hover_color' => '#021447',
            ],
            [
                'title' => 'Special Offer - Summer Sale',
                'badge' => '🔥 Hot Deal',
                'description' => 'Get up to 50% off on selected security products. Limited time offer!',
                'image' => $images[4],
                'button_text' => 'Grab Deal',
                'button_url' => '/products',
                'order' => 4,
                'status' => 'active',
                'start_date' => now()->subDays(2),
                'end_date' => now()->addMonths(3),
                'stat1_label' => 'Discount',
                'stat1_value' => '50%',
                'stat2_label' => 'Products',
                'stat2_value' => '100+',
                'stat3_label' => 'Time Left',
                'stat3_value' => '3 Days',
                'text_color' => '#FFFFFF',
                'bg_color' => '#CC2717',
                'button_color' => '#FFFFFF',
                'button_hover_color' => '#E5E6E9',
            ],
            [
                'title' => 'Smart Home Security',
                'badge' => '💡 Smart Choice',
                'description' => 'Complete smart home security solutions with mobile app control',
                'image' => $images[5],
                'button_text' => 'Explore',
                'button_url' => '/products',
                'order' => 5,
                'status' => 'active',
                'start_date' => now()->subDays(7),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Smart Devices',
                'stat1_value' => '50+',
                'stat2_label' => 'App Rating',
                'stat2_value' => '4.8★',
                'stat3_label' => 'Support',
                'stat3_value' => '24/7',
                'text_color' => '#FFFFFF',
                'bg_color' => '#03246E',
                'button_color' => '#0658DC',
                'button_hover_color' => '#0637A1',
            ],
            [
                'title' => 'Premium Engineering Solutions',
                'badge' => '🏆 Premium Quality',
                'description' => 'Top-tier engineering products with unmatched quality and reliability',
                'image' => $images[2],
                'button_text' => 'View Collection',
                'button_url' => '/products',
                'order' => 6,
                'status' => 'active',
                'start_date' => now()->subDays(4),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Quality',
                'stat1_value' => '100%',
                'stat2_label' => 'Certified',
                'stat2_value' => 'ISO',
                'stat3_label' => 'Warranty',
                'stat3_value' => '5 Years',
                'text_color' => '#FFFFFF',
                'bg_color' => '#0D1B2A',
                'button_color' => '#0637A1',
                'button_hover_color' => '#03246E',
            ],
            [
                'title' => 'Winter Sale - Up to 40% Off',
                'badge' => '❄️ Winter Sale',
                'description' => 'Grab the best deals on security and engineering products this winter',
                'image' => $images[11],
                'button_text' => 'Shop Sale',
                'button_url' => '/products',
                'order' => 7,
                'status' => 'active',
                'start_date' => now()->subDays(8),
                'end_date' => now()->addMonths(2),
                'stat1_label' => 'Discount',
                'stat1_value' => '40%',
                'stat2_label' => 'Items',
                'stat2_value' => '200+',
                'stat3_label' => 'Days Left',
                'stat3_value' => '15',
                'text_color' => '#FFFFFF',
                'bg_color' => '#1a365d',
                'button_color' => '#CC2717',
                'button_hover_color' => '#8B1A0F',
            ],
            [
                'title' => 'Smart Agriculture Solutions',
                'badge' => '🌾 Agri-Tech',
                'description' => 'Modern farming solutions with advanced agricultural machinery',
                'image' => $images[9],
                'button_text' => 'Explore Agri Products',
                'button_url' => '/products',
                'order' => 8,
                'status' => 'active',
                'start_date' => now()->subDays(9),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Machines',
                'stat1_value' => '50+',
                'stat2_label' => 'Farmers',
                'stat2_value' => '1000+',
                'stat3_label' => 'Warranty',
                'stat3_value' => '3 Years',
                'text_color' => '#FFFFFF',
                'bg_color' => '#276749',
                'button_color' => '#0658DC',
                'button_hover_color' => '#0637A1',
            ],
            [
                'title' => 'GPS Tracking Solutions',
                'badge' => '📍 Track & Secure',
                'description' => 'Real-time GPS tracking for vehicles, assets, and loved ones',
                'image' => $images[7],
                'button_text' => 'Shop GPS Trackers',
                'button_url' => '/products',
                'order' => 9,
                'status' => 'active',
                'start_date' => now()->subDays(11),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Trackers',
                'stat1_value' => '20+',
                'stat2_label' => 'Accuracy',
                'stat2_value' => '99%',
                'stat3_label' => 'Support',
                'stat3_value' => '24/7',
                'text_color' => '#FFFFFF',
                'bg_color' => '#2d3748',
                'button_color' => '#0637A1',
                'button_hover_color' => '#03246E',
            ],
            [
                'title' => 'Emergency & Fire Safety',
                'badge' => '🔥 Fire Safety',
                'description' => 'Complete fire extinguisher and emergency safety equipment',
                'image' => $images[13],
                'button_text' => 'View Fire Safety',
                'button_url' => '/products',
                'order' => 10,
                'status' => 'active',
                'start_date' => now()->subDays(12),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Products',
                'stat1_value' => '30+',
                'stat2_label' => 'Certified',
                'stat2_value' => 'ISO',
                'stat3_label' => 'Response',
                'stat3_value' => 'Fast',
                'text_color' => '#FFFFFF',
                'bg_color' => '#CC2717',
                'button_color' => '#FFFFFF',
                'button_hover_color' => '#E5E6E9',
            ],
            [
                'title' => 'Motorcycle Accessories',
                'badge' => '🏍️ Ride Safe',
                'description' => 'Premium motorcycle accessories for style, safety, and performance',
                'image' => $images[8],
                'button_text' => 'Shop Accessories',
                'button_url' => '/products',
                'order' => 11,
                'status' => 'active',
                'start_date' => now()->subDays(13),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Products',
                'stat1_value' => '100+',
                'stat2_label' => 'Brands',
                'stat2_value' => '15+',
                'stat3_label' => 'Warranty',
                'stat3_value' => '1 Year',
                'text_color' => '#FFFFFF',
                'bg_color' => '#1a202c',
                'button_color' => '#CC2717',
                'button_hover_color' => '#8B1A0F',
            ],
            [
                'title' => 'Electrical Solutions',
                'badge' => '⚡ Power Up',
                'description' => 'Complete electrical equipment and solutions for all needs',
                'image' => $images[12],
                'button_text' => 'View Electrical',
                'button_url' => '/products',
                'order' => 12,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Products',
                'stat1_value' => '200+',
                'stat2_label' => 'Brands',
                'stat2_value' => '25+',
                'stat3_label' => 'Warranty',
                'stat3_value' => '2 Years',
                'text_color' => '#FFFFFF',
                'bg_color' => '#021447',
                'button_color' => '#0637A1',
                'button_hover_color' => '#03246E',
            ],
            [
                'title' => 'Construction Materials',
                'badge' => '🏗️ Build Strong',
                'description' => 'Premium construction materials for building and infrastructure',
                'image' => $images[11],
                'button_text' => 'View Materials',
                'button_url' => '/products',
                'order' => 13,
                'status' => 'active',
                'start_date' => now()->subDays(15),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Materials',
                'stat1_value' => '150+',
                'stat2_label' => 'Quality',
                'stat2_value' => 'Premium',
                'stat3_label' => 'Supply',
                'stat3_value' => '24/7',
                'text_color' => '#FFFFFF',
                'bg_color' => '#4a5568',
                'button_color' => '#0637A1',
                'button_hover_color' => '#03246E',
            ],
            [
                'title' => 'Security Camera Systems',
                'badge' => '📹 Watch Over',
                'description' => 'Advanced security camera systems for home and business protection',
                'image' => $images[14],
                'button_text' => 'Shop Cameras',
                'button_url' => '/products',
                'order' => 14,
                'status' => 'active',
                'start_date' => now()->subDays(16),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Cameras',
                'stat1_value' => '30+',
                'stat2_label' => 'Resolution',
                'stat2_value' => '4K',
                'stat3_label' => 'Storage',
                'stat3_value' => '1TB',
                'text_color' => '#FFFFFF',
                'bg_color' => '#1a202c',
                'button_color' => '#0658DC',
                'button_hover_color' => '#0637A1',
            ],
            [
                'title' => 'Industrial Automation',
                'badge' => '🤖 Smart Factory',
                'description' => 'Automation solutions for modern industrial manufacturing',
                'image' => $images[15],
                'button_text' => 'Learn More',
                'button_url' => '/products',
                'order' => 15,
                'status' => 'active',
                'start_date' => now()->subDays(17),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Systems',
                'stat1_value' => '50+',
                'stat2_label' => 'Efficiency',
                'stat2_value' => '95%',
                'stat3_label' => 'Support',
                'stat3_value' => '24/7',
                'text_color' => '#FFFFFF',
                'bg_color' => '#0637A1',
                'button_color' => '#0658DC',
                'button_hover_color' => '#0637A1',
            ],
            [
                'title' => 'CCTV & Surveillance',
                'badge' => '🎥 See Everything',
                'description' => 'Complete CCTV and surveillance solutions for maximum security',
                'image' => $images[3],
                'button_text' => 'View CCTV',
                'button_url' => '/products',
                'order' => 16,
                'status' => 'active',
                'start_date' => now()->subDays(18),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Cameras',
                'stat1_value' => '40+',
                'stat2_label' => 'Coverage',
                'stat2_value' => '360°',
                'stat3_label' => 'Warranty',
                'stat3_value' => '3 Years',
                'text_color' => '#FFFFFF',
                'bg_color' => '#2d3748',
                'button_color' => '#CC2717',
                'button_hover_color' => '#8B1A0F',
            ],
            [
                'title' => 'Mechanical Engineering',
                'badge' => '⚙️ Precision',
                'description' => 'Precision mechanical engineering products and solutions',
                'image' => $images[1],
                'button_text' => 'Shop Mechanical',
                'button_url' => '/products',
                'order' => 17,
                'status' => 'active',
                'start_date' => now()->subDays(19),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Products',
                'stat1_value' => '100+',
                'stat2_label' => 'Precision',
                'stat2_value' => '99.9%',
                'stat3_label' => 'Warranty',
                'stat3_value' => '5 Years',
                'text_color' => '#FFFFFF',
                'bg_color' => '#4a5568',
                'button_color' => '#0637A1',
                'button_hover_color' => '#03246E',
            ],
            [
                'title' => 'Fire Extinguisher Systems',
                'badge' => '🧯 Fire Safety',
                'description' => 'Complete fire extinguisher systems for home, office, and industry',
                'image' => $images[13],
                'button_text' => 'View Extinguishers',
                'button_url' => '/products',
                'order' => 18,
                'status' => 'active',
                'start_date' => now()->subDays(20),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Types',
                'stat1_value' => '10+',
                'stat2_label' => 'Certified',
                'stat2_value' => 'ISO',
                'stat3_label' => 'Response',
                'stat3_value' => 'Fast',
                'text_color' => '#FFFFFF',
                'bg_color' => '#CC2717',
                'button_color' => '#FFFFFF',
                'button_hover_color' => '#E5E6E9',
            ],
            [
                'title' => 'Global Engineering Solutions',
                'badge' => '🌍 Global Reach',
                'description' => 'International quality engineering products with local support',
                'image' => $images[0],
                'button_text' => 'Learn More',
                'button_url' => '/products',
                'order' => 19,
                'status' => 'active',
                'start_date' => now()->subDays(21),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Countries',
                'stat1_value' => '10+',
                'stat2_label' => 'Products',
                'stat2_value' => '500+',
                'stat3_label' => 'Support',
                'stat3_value' => '24/7',
                'text_color' => '#FFFFFF',
                'bg_color' => '#021447',
                'button_color' => '#0637A1',
                'button_hover_color' => '#03246E',
            ],
            [
                'title' => 'Smart Technology Solutions',
                'badge' => '💻 Tech Innovator',
                'description' => 'Cutting-edge smart technology solutions for modern living',
                'image' => $images[14],
                'button_text' => 'Explore Tech',
                'button_url' => '/products',
                'order' => 20,
                'status' => 'active',
                'start_date' => now()->subDays(22),
                'end_date' => now()->addMonths(6),
                'stat1_label' => 'Solutions',
                'stat1_value' => '50+',
                'stat2_label' => 'Innovation',
                'stat2_value' => '100%',
                'stat3_label' => 'Support',
                'stat3_value' => '24/7',
                'text_color' => '#FFFFFF',
                'bg_color' => '#0D1B2A',
                'button_color' => '#0658DC',
                'button_hover_color' => '#0637A1',
            ],
        ];

        foreach ($banners as $banner) {
            Banner::updateOrCreate(
                ['title' => $banner['title']],
                $banner
            );
        }

        $this->command->info('Banners created: ' . Banner::count());
    }
}
